services:

  backend:
    build: ./backend
    container_name: backend

    ports:
      - "8085:8085"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/employee_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  frontend:
    build: ./frontend
    container_name: frontend

    ports:
      - "80:80"

    depends_on:
      - backend